version: '3.9'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ./CODIGO:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incidencias_tic
      MYSQL_USER: admindb
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./BD:/docker-entrypoint-initdb.d # Mapea el directorio con el archivo .sql al contenedor

volumes:
  db_data:
